import matplotlib.pyplot as plt
import numpy as np
import os
import shutil
import logging
import argparse
import h5py
from tqdm import tqdm

from rfsoc_rfdc.dsp.ofdm import OFDM
from rfsoc_rfdc.rfdc_config import ZCU216_CONFIG
from rfsoc_rfdc.dsp.detection import Detection


class MIMODetection(Detection):

    def __init__(self, sample_rate=1e9, tx_num=2, rx_num=2, MCS=0, debug_mode=False):
        super().__init__(sample_rate=sample_rate, debug_mode=debug_mode)
        # Initialize with dimension
        self.MCS = MCS
        # Tx/Rx MIMO dimension
        self.tx_num = tx_num
        self.rx_num = rx_num
        # Tx/Rx file name
        self.txFile = f"waveTx_{self.tx_num}_{self.MCS}.mat"
        self.rxFile = f"waveRx_{self.rx_num}_{self.MCS}.mat"
        # Initialize processing variables
        self.packet_len = None
        self.pad_len = None

    def proc_tx(self, packet_tx_list):
        """
        Process transmission for MIMO.
        packet_tx_list: shape (tx_num, packet_len)
        """
        # Update vars
        self.packet_len = packet_tx_list.shape[1]
        self.pad_len = 10000

        head_len = sum(self.zadoff_set) * 3

        # Generate Preamble
        head_tx = np.zeros(head_len, dtype=np.complex64)
        offset = 0
        for zadoff_len in self.zadoff_set:
            zadoff_single = np.exp(
                1j * 2 * np.pi * np.random.rand(1, zadoff_len))
            zadoff_double = np.tile(zadoff_single, 2)
            head_tx[offset:offset + 2 * zadoff_len] = zadoff_double
            offset += 3 * zadoff_len

        pad_tx = np.zeros(self.pad_len, dtype=np.complex64)

        wave_tx_list = []
        for tx_idx in range(self.tx_num):
            packet_tx = packet_tx_list[tx_idx, :]
            self._check_saturation(packet_tx)

            wave_tx = np.concatenate(
                (pad_tx, head_tx, packet_tx, pad_tx), axis=0)
            wave_tx_list.append(wave_tx)

        return np.vstack(wave_tx_list)

    def proc_rx(self, wave_rx):
        """Detect preamble and extract packets from multiple Rx channels"""

        if self.packet_len is None:
            # Try to infer or warn if packet_len is not set
            logging.warning(
                "MIMODetection: packet_len not set. Ensure proc_tx was called or set manually.")
            return None, None, None

        packet_rx_list = np.zeros(
            (self.rx_num, self.packet_len), dtype=np.complex64)
        snr_list = np.full(self.rx_num, np.nan)
        cfo_list = np.full(self.rx_num, np.nan)

        # Path to the default plot generated by Detection.proc_rx
        default_plot_name = ZCU216_CONFIG['CONFIG_NAME'] + '_detection.png'
        default_plot_path = self.logger.get_file_path(default_plot_name)

        for rx_idx in range(self.rx_num):
            wave_stream = wave_rx[rx_idx, :]

            # Delegate to parent class for detection, CFO, extraction, and SNR
            # This will also generate a plot at default_plot_path
            packet_rx, snr, cfo = super().proc_rx(wave_stream)

            if packet_rx is not None:
                packet_rx_list[rx_idx, :] = packet_rx
                snr_list[rx_idx] = snr
                cfo_list[rx_idx] = cfo

                # Rename the plot generated by parent class to channel-specific name
                if os.path.exists(default_plot_path):
                    fprefix = f"{ZCU216_CONFIG['CONFIG_NAME']}_CH{rx_idx}_MCS{self.MCS}"
                    target_name = fprefix + "_detection.png"
                    target_path = self.logger.get_file_path(target_name)
                    shutil.move(default_plot_path, target_path)

                    # Save log (MIMO specific requirement)
                    log_file = self.logger.get_file_path(fprefix + "_res.log")
                    with open(log_file, 'w') as f:
                        f.write(f"{snr:.3f}, {cfo:.3f}")
            else:
                if self.debug_mode:
                    logging.warning(f"CH #{rx_idx}: Failed to detect packet")

        return packet_rx_list, snr_list, cfo_list


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description='MIMO OFDM Detection Algorithm')
    parser.add_argument('--mode', type=str, default='simulate',
                        choices=['simulate', 'h5file'],
                        help='Mode: simulate (generate test waveform) or h5file (load from h5 file)')
    parser.add_argument('--h5_file', type=str, default=None,
                        help='Path to h5 file containing waveform data')
    parser.add_argument('--h5_dataset', type=str, default='iq_samples',
                        help='Dataset name in h5 file (default: iq_samples)')
    parser.add_argument('--tx_num', type=int, default=2,
                        help='Number of Tx channels')
    parser.add_argument('--rx_num', type=int, default=2,
                        help='Number of Rx channels')
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO,
                        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')

    np.random.seed(0)

    # OFDM Configuration
    ofdm = OFDM(sym_num=100, fft_size=64, sub_num=48,
                modu='16QAM', cp_rate=0.125)

    # Generate base packet
    packet_tx_base = ofdm.generate()

    # Create MIMO packet list (duplicate for simulation)
    packet_tx_list = np.tile(packet_tx_base, (args.tx_num, 1))

    # Initialize Detector
    mimo_det = MIMODetection(
        sample_rate=2.5e9, tx_num=args.tx_num, rx_num=args.rx_num, debug_mode=True)

    # Process Tx (Add Preamble)
    wave_tx_mimo = mimo_det.proc_tx(packet_tx_list)

    if args.mode == 'simulate':
        logging.info("Running in simulation mode...")

        # Add Noise
        noise = 0.001 * (np.random.randn(*wave_tx_mimo.shape) +
                         1j * np.random.randn(*wave_tx_mimo.shape))
        wave_tx_noisy = wave_tx_mimo + noise

        # Simulate Loopback (repeat waveform to mimic stream)
        # We need to repeat along the time axis (axis 1)
        wave_rx_mimo = np.tile(wave_tx_noisy, (1, 4))

        # If rx_num != tx_num, handle mapping (simple case: direct mapping or truncation)
        if args.rx_num != args.tx_num:
            logging.warning(
                "Tx != Rx num in simulation. Using 1:1 mapping for available channels.")
            if args.rx_num > args.tx_num:
                # Pad with zeros or wrap around
                wave_rx_mimo = np.pad(
                    wave_rx_mimo, ((0, args.rx_num - args.tx_num), (0, 0)), mode='wrap')
            else:
                # Truncate
                wave_rx_mimo = wave_rx_mimo[:args.rx_num, :]

    elif args.mode == 'h5file':
        if args.h5_file is None:
            raise ValueError(
                "--h5_file argument is required when mode is 'h5file'")

        if not os.path.exists(args.h5_file):
            raise FileNotFoundError(f"H5 file not found: {args.h5_file}")

        logging.info(f"Loading waveform from h5 file: {args.h5_file}")

        with h5py.File(args.h5_file, 'r') as f:
            if args.h5_dataset not in f:
                raise KeyError(
                    f"Dataset '{args.h5_dataset}' not found in h5 file")

            wave_rx = f[args.h5_dataset][:]

            # Handle dimensions: expect (channels, samples) or (samples, channels)
            # Standard convention here seems to be (channels, samples) based on proc_rx
            if wave_rx.ndim == 2:
                if wave_rx.shape[0] > wave_rx.shape[1] and wave_rx.shape[1] == args.rx_num:
                    # Transpose if (samples, channels)
                    wave_rx = wave_rx.T

            wave_rx_mimo = wave_rx
            logging.info(f"Loaded waveform shape: {wave_rx_mimo.shape}")

    # Process Rx
    packet_rx_list, snr_list, cfo_list = mimo_det.proc_rx(wave_rx_mimo)

    # Analyze results
    for i in range(args.rx_num):
        packet_rx = packet_rx_list[i, :]
        if np.all(packet_rx == 0):
            logging.warning(f"CH #{i}: No packet extracted.")
            continue

        evm, ber = ofdm.analyze(packet_rx)
        logging.info(
            f"CH #{i} - SNR: {snr_list[i]:.2f} dB, CFO: {cfo_list[i]:.2f} Hz, EVM: {evm:.5f}, BER: {ber:.5f}")

    logging.info('Done!')
